--- #YAML:1.0
name:               re-engine-LPEG
version:            0.05
abstract:           LPEG regular expression engine
author:
    - Francois PERRAD <francois.perrad@gadz.org>
license:            MIT
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Warn:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
